# Generated by Django 5.2.4 on 2025-07-19 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('interest', 'Interest'), ('skill', 'Skill'), ('event_type', 'Event Type'), ('location', 'Location'), ('activity', 'Activity')], default='interest', max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tags_tagged_content_eaa81e_idx')],
                'unique_together': {('tag', 'content_type', 'object_id')},
            },
        ),
    ]
