# Generated by Django 5.2.4 on 2025-07-19 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Personal bio or description'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='duration_months',
            field=models.IntegerField(default=12, help_text='Duration in months'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as default for new members'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
