# Generated by Django 5.2.4 on 2025-07-19 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_membershiptype_options_memberprofile_address_and_more'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='is_authorized',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='member_profiles', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='benefits_list',
            field=models.TextField(blank=True, help_text='List of benefits for this membership type'),
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('benefit_type', models.CharField(choices=[('event_access', 'Event Access'), ('digital_content', 'Digital Content'), ('workspace_access', 'Workspace Access'), ('networking', 'Networking'), ('training', 'Training'), ('mentoring', 'Mentoring')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership_types', models.ManyToManyField(related_name='available_benefits', to='members.membershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='MemberBenefitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.benefit')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_usage', to='members.memberprofile')),
            ],
            options={
                'unique_together': {('member', 'benefit', 'used_at')},
            },
        ),
    ]
