# Generated by Django 5.2.4 on 2025-07-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_memberprofile_is_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='membership_category',
            field=models.CharField(choices=[('community', 'Community Members'), ('key_access', 'Key Access Members'), ('creative_workspace', 'Creative Workspace Members')], default='community', max_length=20),
        ),
    ]
